name: deploy-blog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true # Checkout private submodules(themes or something else).
    - name: Set timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Taipei"
    
    - name: Cache node modules
      uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      #run: npm install

    # Deploy hexo blog website.
    - name: Deploy
      id: deploy
      uses: PttCodingMan/hexo-action@master
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        #user_name: your github username  # (or delete this input setting to use bot account)
        #user_email: your github useremail  # (or delete this input setting to use bot account)
        #commit_msg: ${{ github.event.head_commit.message }}  # (or delete this input setting to use hexo default settings)
    # Use the output from the `deploy` step(use for test action)
    - name: Get the output
      run: |
        echo "${{ steps.deploy.outputs.notify }}"
